Add report/unreport to post & comment, discussion needed
ucf-tower-app/xplat pull request #176
Opened 2023-02-03 20:13 UTC by Henry-Graves

# Describe your changes
Made xplat functions addReport, removeReport, reportedBy (to check if given user has reported the content).
Reports are stored in a new Firebase collection. 
I didn't make a new type for reports but can change that if it's a big deal.

@JakeSteinebronn @tylerhm @abrugal  For auto-hiding content after 3 reports I'm gonna add a boolean "hiddenByReports". Do want to filter out that content when fetching or client-side? I think it should be a front-end check.

# Issue ticket number and link
Finishes some sub-tasks for #105

Next up: auto-hide content, employee actions.

2023-02-03 21:09 UTC, JakeSteinebronn commented
for auto-hiding, we can have the report transaction also increment a counter on every post like `numReports` (and when a report is resolved, it decrements this count)

Then, front-end can just (JUST) check if that number is gequal to some const, like 3 or 5 or whatever.

What do you think

2023-02-03 21:14 UTC, Henry-Graves commented
That would work, the report list is currently a field on every post & comment so front-end can check the size of the list.
It saves us from storing an extra bool on every post/comment, but is probably a bit more annoying to use. I think I'd rather keep an updated bool

2023-02-03 22:33 UTC, JakeSteinebronn commented
Well you wouldn't ever need the bool, you could have your `checkShouldBeHidden` just do the count / length check. I also think we don't need to maintain the actual array of the reports, just the reports themselves

2023-02-03 22:37 UTC, JakeSteinebronn requested changes
I think this can be considerably cleaner if we move it into user. something like

`User::reportContent(content: Post | Comment | User) {}`
Since really, all you need is the docref of the content, and they all extend lazy object, and you can just add the `reportedBy[]` list to these 3 types and it'll all work out.

2023-02-04 19:05 UTC, Henry-Graves commented
I moved the redundant functions to User, but didn't opt to support reporting a User itself, it'll keep reporting simpler for employees because they won't see a reported user then have to dig through all their content to find why they're reported.

added checkShouldBeHidden() to Post and Comment

also simplified the code for the functions by checking if they have data & getting data at the top of the functions

2023-02-06 15:47 UTC, JakeSteinebronn commented
We can get to this later, but user reporting should be implemented if their avatar, displayname, or bio is inappropriate

2023-02-06 15:48 UTC, Henry-Graves commented
oh true I'll add that next then

2023-02-06 15:52 UTC, JakeSteinebronn requested changes

2023-02-06 15:52 UTC, JakeSteinebronn commented on types/user.ts
> +    return runTransaction(db, async (transaction: Transaction) => {
Don't we also have to update `content`'s `reports` array to remove this user docref?

2023-02-06 15:52 UTC, JakeSteinebronn commented on types/user.ts
> +    return runTransaction(db, async (transaction: Transaction) => {
Don't we have to add to `content`'s `reports` array ?

2023-02-06 16:49 UTC, JakeSteinebronn approved these changes

2023-02-06 17:25 UTC, tylerhm commented
> Do want to filter out that content when fetching or client-side?

Front-end check sounds good to me :)

2023-02-06 17:27 UTC, merged